Add optional poll() implementation under MG_ENABLE_POLL define
cesanta/mongoose pull request #1561
Opened 2022-05-24 21:53 UTC by vkoskiv

This adds the ability to substitute `select()` with `poll()` on supported
unix environments when `MG_ENABLE_POLL` is defined. A make flag called
`USE_POLL` is provided as well.
Using `poll()` removes the limitation of `FD_SETSIZE` concurrent sockets,
generally 1024 on Linux environments.

Tested with `make test IPV6=0 USE_POLL=1`
Marked as `draft` because I have not debugged a strange issue where substituting the call to `malloc()` in `mg_iotest()` with `alloca()` (as suggested by @cpq) results in the `test_http_client` and `test_dns_error` tests to fail.

2022-05-24 22:44 UTC, cpq requested changes
1. C++ needs some type casts - use `make clean all IPV6=0` to check
2. Make `MG_ENABLE_POLL` like the rest of `MG_ENABLE_*` vars:
   - define if in `src/config.h` as

```c
#ifndef MG_ENABLE_POLL
#define MG_ENABLE_POLL 0
#endif
```

And in the arch_unix.h, 

```c
#if MG_ENABLE_POLL
#include ...
#else
#include ... 
#endif
```

3. No need to path Makefile. You can `make clean test IPV6=0 TFLAGS=-DMG_ENABLE_POLL=1`

2022-05-24 22:48 UTC, cpq commented on src/sock.c
> +  for (c = mgr->conns; c != NULL; c = c->next) {
If you stick i++ into the for(), then you don't need to care about increments in the loop body
for (c = mgr->conns; c != NULL; c = c->next, i++)

2022-05-24 22:50 UTC, cpq commented on src/sock.c
> +#ifdef MG_ENABLE_POLL
#if MG_ENABLE_POLL

2022-05-25 10:21 UTC, cpq commented
Integrated this change, thank you @vkoskiv

2022-05-25 12:09 UTC, vkoskiv commented
Thanks @cpq, I would have preferred to retain authorship of the changes, but at least the issue is now resolved :+1:

2022-05-26 03:02 UTC, vkoskiv commented
Alright, thanks for the good feedback! I amended the commit from before with your suggestions. Let me know if you have any more.
Tests pass now, and I also did some stress testing with 9000 concurrent websocket connections, and things worked fine.

2022-05-26 06:53 UTC, merged