enhanced path sanitizing
cesanta/mongoose pull request #2284
Opened 2023-06-30 11:16 UTC by robertc2000

2023-06-30 12:27 UTC, scaprile requested changes

2023-06-30 12:27 UTC, scaprile commented on src/str.c
> +          }
Code-style: Whenever there is an `else` clause, use braces for both then and else paths. The else goes on the same line as the brace, short functions can be read without scrolling. Please run clang-format

Is there a reason I'm missing for the second `if` ? The `else` action is the same for both nested `if`s, why not keep the `&&` as before ?

If possible, I would add a test case in the unit tests, to make sure this works.

2023-07-03 09:45 UTC, cpq requested changes

2023-07-03 09:45 UTC, cpq commented on src/http.c
> +  if (!mg_path_is_sane(path)) {
Please simplify this:

```c
if (!mg_path_is_sane(path)) {
  mg_http_reply(c, 418, "", "Invalid path");
  return -1;
}
```

2023-07-03 09:45 UTC, cpq commented on src/http.c
>    if (n > path_size) n = path_size;
Fail here, too. There is no point truncating the path.

```c
if (n > path_size) {
  mg_http_reply(c, 418, "", "path is too big");
  return -1;
}
```

2023-07-03 09:45 UTC, cpq commented on src/http.c
> +  if (n + 2 < path_size && path[n-1] != '/') path[n++] = '/', path[n] = '\0';
Please add a comment here
```c
// Terminate root dir with /
```

2023-07-03 12:53 UTC, scaprile commented on examples/file-upload-multiple-posts/main.c
> +        mg_http_reply(c, 400, "", "%s", "invalid path");
As per the comment below on http.c, shouldn't this one also be 418 ?

2023-07-03 12:56 UTC, robertc2000 commented on test/unit_test.c
> +        mg_http_reply(c, 400, "", "%s", "invalid path");
Isn't 400 more relevant than 418?

2023-07-03 12:56 UTC, scaprile commented on test/unit_test.c
> +  ASSERT(fetch(&mgr, buf, url, "GET /..%%2ffuzz.c%%20 HTTP/1.0\n\n") == 400);
418 ?

2023-07-03 13:05 UTC, scaprile commented on test/unit_test.c
> +        mg_http_reply(c, 400, "", "%s", "invalid path");
If we consider "deceptive routing path", probably yes.
We are not a teapot anyway... and 403 is more appropriate for blocking.

2023-07-03 13:43 UTC, merged