Fix #2292 - fail on stray \r character in headers
cesanta/mongoose pull request #2294
Opened 2023-07-07 11:35 UTC by cpq

2023-07-07 13:28 UTC, scaprile requested changes
Minor doubts

2023-07-07 13:28 UTC, scaprile commented on src/http.c
> +  if (s >= end || *s++ != '\n') return false;
251: Here `s < end`, otherwise it would have exit at line 250
252: We already checked for that, didn't we ? This looks like the right side of 250 to me. I think this would collapse to `if (s == end) return false;`
249 stops at first eol or buffer overflow. Then we check if it is an actual eol and exit on overflow or stray cr. I think 251 and 252 are redundant, that was already covered by 250.
This won't allow spaces after PROTO, hope that is correct.

2023-07-07 13:28 UTC, scaprile commented on src/http.c
> +    if (s >= end || *s++ != '\n') return false;
Same comment as 251 below.

2023-07-07 13:29 UTC, scaprile commented on src/http.c
> +    if (s >= end || *s++ != '\n') return false;
Well, "below" in code... GH posted my comments in the order I made them...

2023-07-09 17:02 UTC, cpq commented on test/unit_test.c
> +  // #2292: fail on stray \n inside the headers
fixed

2023-07-09 17:11 UTC, cpq commented on src/http.c
> +  if (s >= end || *s++ != '\n') return false;
The only redundant check is 251, because 251 does `s++` and thus it can become `s == end`
We do allow spaces in hm->proto, cause we skip until newline

2023-07-09 22:08 UTC, merged