improved tcp closure
cesanta/mongoose pull request #2344
Opened 2023-08-15 14:30 UTC by robertc2000

2023-08-15 15:46 UTC, scaprile requested changes

2023-08-17 11:40 UTC, scaprile commented on src/tcpip/tcpip.c
> +  //mg_hexdump(pkt->raw.ptr, pkt->raw.len);
leftover

2023-08-17 11:44 UTC, scaprile commented on test/mip_tap_test.c
> +#define MG_USING_DHCP 0
Reason ?

2023-08-17 12:11 UTC, scaprile approved these changes

2023-08-17 12:15 UTC, robertc2000 commented on test/mip_tap_test.c
> +  usleep(1000000);             // Waiting until all connections finally close
We call the manager before in the fetch function when we initiate the TCP closure and start the timeout for the connection to be deleted. Therefore, before calling the manager at the end we have to wait this maximum amount of time until we are sure all the connections are freed.

2023-08-17 21:30 UTC, cpq approved these changes

2023-08-18 11:06 UTC, merged