IP fragmentation send path: added TCP/UDP packet splitting to fit within MTU
cesanta/mongoose pull request #2380
Opened 2023-09-08 12:07 UTC by robertc2000

2023-09-08 13:19 UTC, scaprile requested changes
The approach seems to look fine for TCP.
However, for UDP, it will only work if the user calls mg_print*() functions that call mg_io_send(). Otherwise, calls to mg_send() will bypass your strategy and be sent without being fragmented. Please write a test that proves or refutes my point and, if I'm right, then solve it.
https://github.com/cesanta/mongoose/blob/d23664a4574caa6316dcb6d27df5fddb4f449ed7/src/net_builtin.c#L1075-L1088

In case we would need to mg_io_add for UDP, I wouldn't want to delay UDP packets that would fit the MTU, so we should not just buffer, as buffered datagrams would be sent on next poll, not now. For UDP, whatever fits the MTU we should try to send it now. (*)
If I'm right, this fragmentation stuff will have the side effect that we'll now be able to "send UDP datagrams larger than an IP datagram", which will cause them to the splitted into several datagrams and that IMO wouldn't be correct. Please check that, too.

(*): How would this interact with an ARP lookup ? Now our first UDP that requires an ARP lookup is lost, can we make use of this in advance and save the datagram for later ? (If the ISO police OSI enforcement unit comes for you, just tell them I told you to do it)

And now that I think of it again... We are not actually sending fragmented IP, are we ? So if a user requests a 1500-byte UDP datagram and our MTU is 750, we'll actually send two UDP datagrams breaking the very logic foundation of UDP datagrams. I think we should either reject this (force the users to break their messages) and (or at least) log it. Otherwise, we should send IP fragments but we will not receive our own data and that looks bad...
Our current logic is to follow down the path and the Ethernet layer will drop too-long packets.
I think this is turning into a long rambling, if that is the case, let's please follow up at the chat.

2023-09-08 13:41 UTC, robertc2000 commented on src/net_builtin.c
> +  while (c->send.len) {
You are right. Solved!

2023-09-08 13:45 UTC, scaprile commented on src/net_builtin.c
> +    }
Please run clang-format

2023-09-08 14:56 UTC, cpq commented on src/net_builtin.c
> +  if (len + max_headers_len - eth_h_len > c->mtu) {
Also, `mtu` must not be too small - it should be bigger that the size of headers. Shall we check that `mtu` is not less than a minimum possible here, or somewhere else?

2023-09-08 14:56 UTC, scaprile commented on src/net.h
> +  uint16_t mtu;                // MTU for this connection
Yeah, I second, missed that, that is ifp-> stuff not c-> ...

2023-09-08 14:57 UTC, cpq requested changes
Please move `mtu` setting to the `struct connstate`

2023-09-11 11:13 UTC, cpq approved these changes

2023-09-11 13:02 UTC, scaprile approved these changes
Please address those nitty comments of mine.

2023-09-11 13:02 UTC, scaprile commented on src/net_builtin.c
> +      MG_ERROR(("UDP datagram exceeds MTU"));
Please tell the datagram has been truncated, something like
"Truncated UDP datagram exceeding MTU"

2023-09-11 13:02 UTC, scaprile commented on src/net_builtin.c
> +      MG_ERROR(("UDP datagram exceeds MTU"));
same comment as above (truncation)

2023-09-11 15:31 UTC, scaprile reviewed
Changes bring more changes...

2023-09-12 11:51 UTC, merged